// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async scanRepositories(rootPath: string, maxDepth: number, showEmptyFolders: boolean) : Promise<RepoInfo[]> {
    return await TAURI_INVOKE("scan_repositories", { rootPath, maxDepth, showEmptyFolders });
},
async refreshRepo(path: string) : Promise<RepoInfo | null> {
    return await TAURI_INVOKE("refresh_repo", { path });
},
async previewScan(rootPath: string, maxDepth: number) : Promise<ScanPreview> {
    return await TAURI_INVOKE("preview_scan", { rootPath, maxDepth });
},
async fetchRepo(path: string) : Promise<Result<FetchResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_repo", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchAll(paths: string[]) : Promise<Result<FetchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_all", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelFetchAll() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_fetch_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadConfig() : Promise<AppConfig> {
    return await TAURI_INVOKE("load_config");
},
async saveConfig(config: AppConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetConfig() : Promise<AppConfig> {
    return await TAURI_INVOKE("reset_config");
},
async getConfigPath() : Promise<string> {
    return await TAURI_INVOKE("get_config_path");
},
async openInExplorer(path: string) : Promise<void> {
    await TAURI_INVOKE("open_in_explorer", { path });
},
async openInEditor(path: string, editor: Editor) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_in_editor", { path, editor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRemoteUrl(remoteUrl: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_remote_url", { remoteUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async copyPath(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async copyCodeCommand(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_code_command", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectAvailableEditors() : Promise<Editor[]> {
    return await TAURI_INVOKE("detect_available_editors");
},
async isFirstRun() : Promise<boolean> {
    return await TAURI_INVOKE("is_first_run");
},
async detectDefaultRepoPath() : Promise<string> {
    return await TAURI_INVOKE("detect_default_repo_path");
},
async platformInfo() : Promise<PlatformInfo> {
    return await TAURI_INVOKE("platform_info");
},
async checkGhAuth() : Promise<GhAuthStatus> {
    return await TAURI_INVOKE("check_gh_auth");
},
async searchGithubRepos(query: string, owner: string | null, limit: number) : Promise<Result<GithubRepoResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_github_repos", { query, owner, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cloneGithubRepo(fullName: string, destParent: string) : Promise<Result<CloneOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clone_github_repo", { fullName, destParent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installRepoDeps(repoPath: string, manager: DepManager) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_repo_deps", { repoPath, manager }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRepoIntegrations(requests: IntegrationRequest[], forceRefresh: boolean) : Promise<Result<RepoIntegration[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repo_integrations", { requests, forceRefresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async invalidateGithubIntegrations() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("invalidate_github_integrations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkForUpdate() : Promise<Result<UpdateInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installUpdate() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AheadBehind = { ahead: number; behind: number; hasUpstream: boolean }
export type AppConfig = { rootPath: string; maxScanDepth: number; showEmptyFolders: boolean; fetchTimeoutSeconds: number; fetchConcurrency: number; theme: Theme; window: WindowState; preferredEditor: Editor; defaultGithubOwner?: string; githubSearchAll?: boolean; githubIntegrationsEnabled?: boolean; updateChannel?: UpdateChannel; language?: Language; version: number }
export type CiState = "success" | "failure" | "pending" | "neutral" | "unknown"
export type CloneOutcome = { clonePath: string; depManager: DepManager | null }
export type CommitInfo = { shortHash: string; subject: string; dateIso: string }
export type DepManager = "yarn" | "npm"
export type Editor = "vsCode" | "vsCodeInsiders" | "cursor" | "zed" | "intelliJ" | "webStorm" | "pyCharm" | "rider" | "fleet" | "sublime" | "neovim" | "vim" | "system"
export type FetchResult = { path: string; success: boolean; message: string }
export type GhAuthStatus = { loggedIn: boolean; ghMissing: boolean; user: string | null }
export type GithubRepoResult = { fullName: string; description: string | null; stars: number; url: string | null }
export type IntegrationRequest = { path: string; remoteUrl: string | null; currentBranch: string | null }
export type Language = "system" | "en" | "fr"
export type PlatformInfo = { os: string; isWsl: boolean; wslDistro: string | null; homeDir: string }
export type RepoInfo = { path: string; relativePath: string; name: string; depth: number; kind: RepoKind; currentBranch: string | null; lastCommit: CommitInfo | null; status: RepoStatus; aheadBehind: AheadBehind | null; remoteUrl: string | null; remoteShort: string | null; children: RepoInfo[] }
export type RepoIntegration = { path: string; owner: string; name: string; prCount: number | null; prUrl: string | null; ciState: CiState | null; ciUrl: string | null; ciWorkflowName: string | null; fetchedAtIso: string }
export type RepoKind = "git" | "submodule" | "parentFolder"
export type RepoStatus = { clean: boolean; modified: number; added: number; deleted: number; renamed: number; untracked: number; conflicted: number; stagedModified: number }
export type ScanPreview = { reposCount: number; foldersCount: number; sample: string[] }
export type Theme = "system" | "light" | "dark"
export type UpdateChannel = "stable" | "beta"
export type UpdateInfo = { version: string; currentVersion: string; date: string | null; body: string | null }
export type WindowState = { width: number; height: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
