// This file is auto-generated by tauri-specta on first debug build.
// Do not edit manually.
import { invoke } from "@tauri-apps/api/core";

export type RepoKind = "git" | "submodule" | "parentFolder";

export interface CommitInfo {
  shortHash: string;
  subject: string;
  dateIso: string;
}

export interface RepoStatus {
  clean: boolean;
  modified: number;
  added: number;
  deleted: number;
  renamed: number;
  untracked: number;
  conflicted: number;
  stagedModified: number;
}

export interface AheadBehind {
  ahead: number;
  behind: number;
  hasUpstream: boolean;
}

export interface RepoInfo {
  path: string;
  relativePath: string;
  name: string;
  depth: number;
  kind: RepoKind;
  currentBranch: string | null;
  lastCommit: CommitInfo | null;
  status: RepoStatus;
  aheadBehind: AheadBehind | null;
  remoteUrl: string | null;
  remoteShort: string | null;
  children: RepoInfo[];
}

export type Theme = "system" | "light" | "dark";

export type Editor =
  | "vsCode"
  | "vsCodeInsiders"
  | "cursor"
  | "zed"
  | "intelliJ"
  | "webStorm"
  | "pyCharm"
  | "rider"
  | "fleet"
  | "sublime"
  | "neovim"
  | "vim"
  | "system";

export interface WindowState {
  width: number;
  height: number;
}

export interface AppConfig {
  rootPath: string;
  maxScanDepth: number;
  showEmptyFolders: boolean;
  fetchTimeoutSeconds: number;
  fetchConcurrency: number;
  theme: Theme;
  window: WindowState;
  preferredEditor: Editor;
  version: number;
}

export interface ScanPreview {
  reposCount: number;
  foldersCount: number;
  sample: string[];
}

export interface FetchResult {
  path: string;
  success: boolean;
  message: string;
}

export type FetchPhase = "queued" | "running" | "done" | "error";

export interface FetchProgress {
  repoPath: string;
  repoName: string;
  phase: FetchPhase;
  message: string | null;
  reposDone: number;
  reposTotal: number;
}

export interface PlatformInfo {
  os: string;
  isWsl: boolean;
  wslDistro: string | null;
  homeDir: string;
}

// Commands
export const commands = {
  scanRepositories: (rootPath: string, maxDepth: number, showEmptyFolders: boolean) =>
    invoke<RepoInfo[]>("scan_repositories", { rootPath, maxDepth, showEmptyFolders }),

  refreshRepo: (path: string) =>
    invoke<RepoInfo | null>("refresh_repo", { path }),

  previewScan: (rootPath: string, maxDepth: number) =>
    invoke<ScanPreview>("preview_scan", { rootPath, maxDepth }),

  fetchRepo: (path: string) =>
    invoke<FetchResult>("fetch_repo", { path }),

  fetchAll: (paths: string[]) =>
    invoke<FetchResult[]>("fetch_all", { paths }),

  cancelFetchAll: () =>
    invoke<void>("cancel_fetch_all"),

  loadConfig: () =>
    invoke<AppConfig>("load_config"),

  saveConfig: (config: AppConfig) =>
    invoke<void>("save_config", { config }),

  resetConfig: () =>
    invoke<AppConfig>("reset_config"),

  getConfigPath: () =>
    invoke<string>("get_config_path"),

  isFirstRun: () =>
    invoke<boolean>("is_first_run"),

  detectDefaultRepoPath: () =>
    invoke<string>("detect_default_repo_path"),

  platformInfo: () =>
    invoke<PlatformInfo>("platform_info"),

  openInExplorer: (path: string) =>
    invoke<void>("open_in_explorer", { path }),

  openInEditor: (path: string, editor: Editor) =>
    invoke<void>("open_in_editor", { path, editor }),

  openRemoteUrl: (remoteUrl: string) =>
    invoke<string>("open_remote_url", { remoteUrl }),

  copyPath: (path: string) =>
    invoke<void>("copy_path", { path }),

  copyCodeCommand: (path: string) =>
    invoke<void>("copy_code_command", { path }),

  detectAvailableEditors: () =>
    invoke<Editor[]>("detect_available_editors"),
};
